### ISSUE TITLE
set_window_state() breaks fullscreen

### ISSUE THREAD

**Issue by Volcanic-Penguin** [raylib-rs/raylib-rs#108]
So to initialize my Raylib game I have this code

```
let (rl, thread) = raylib::init()
    .size(0, 0)
    .fullscreen() // <------- !!!!!!!!!!!!!!!
    .undecorated()
    .title("xxxxxxx")
    .vsync()
    .build();
```

I then do the following to set FLAG_WINDOW_ALWAYS_RUN to true, so that the game runs when minimized

`rl.set_window_state(rl.get_window_state().set_window_always_run(true));`

This works but it breaks the fullscreen for some reason so that I then have to run 

`rl.toggle_fullscreen();`

First off all, am I using `set_window_state()` correctly? I tried just doing this 

`rl.get_window_state().set_window_always_run(true);`

But it had no effect, so I assume I need to pass the `WindowState` into `set_window_state()`. An interesting difference here between this function and the Raylib C function is that the C function just takes a config flag not a whole `WindowState` struct, like this

`SetWindowState(FLAG_WINDOW_ALWAYS_RUN);`

Is it correct that `set_window_state()` should take a `WindowState` instead of `ConfigFlags` enum like `ConfigFlags::FLAG_WINDOW_ALWAYS_RUN`?

**Comment by IoIxD** [comment]
In all these cases (including `get_window_state` which I don't think returns a mutable reference to the window state, hence `set_window_state`, I don't even know why those functions exist if they do nothing) we are calling Raylib functions directly, so it's most likely a Raylib bug.

Can you compile/reproduce the bug on C Raylib 5.0? Version 5.0 is important in case this was fixed in 5.5 which we haven't finish binding yet (although it seems like this might not have been reported)

**Comment by Volcanic-Penguin** [comment]
Wow as someone who isn't a C developer, it was a lot harder than I thought to get a hello world app up and running with Raylib and C. In the end using the Zig C compiler made it a lot easier. 

Anyway, yes it turns out that it's a bug in C Raylib 5.0 as well as 5.5.

**Comment by IoIxD** [comment]
Should've provided code/the gcc command to do it, my bad.

**Comment by Volcanic-Penguin** [comment]
Hah no worries
